-- Database: GLOBALPLA Metadata version: 2 Exported: May 27, 2020
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5986_MVE_TKT_SU" USING 'GCG_5986_MVE_TKT_SU.mkd' PAGESIZE=4096 (
 "TRMNL" CHAR(3) NOT NULL,
 "COMMENTS" LONGVARCHAR NOT NULL,
 "PRINTER" CHAR(100),
 "PRINT_QTY" NUMERIC(3,0),
 "SCRAPPRINTER" CHAR(100) );
-- End Multi-Line Statement
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
